version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  flyway:
    image: flyway/flyway:9.3
    restart: "no"
    command: -url=jdbc:mysql://db -schemas=airport -user=${DB_USERNAME} -password=${DB_PASSWORD} -connectRetries=60 migrate
    environment:
      - FLYWAY_PLACEHOLDERS_DATABASE=${DB_DATABASE}
    env_file:
      - .env
    volumes:
      - ./custom/db/migrations:/flyway/sql
    depends_on:
      - db

  directus:
    image: directus/directus:9.0
    restart: unless-stopped
    ports:
      - 8055:8055
    depends_on:
      - db
      - flyway
    environment:
      DB_CLIENT: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}
    env_file:
      - .env

  api:
    build: ./packages/airportart-api/
    restart: unless-stopped
    ports:
      - 3000:80
    environment:
      - PORT=80
      - DB_HOST=db
      - DB_NAME=${DB_DATABASE}
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    depends_on:
      - db

  web:
    build: ./packages/airportart-web/
    restart: unless-stopped
    ports:
      - 3001:80
    depends_on:
      - api

volumes:
  mysql:
